public class greenhouseMappingWrapper {
    
    @AuraEnabled
    public String salesforceObjName{get;set;}
    
    @AuraEnabled
    public String salesforceField{get;set;}
    
    @AuraEnabled
    public String greenhouseObjName{get;set;}
    
    @AuraEnabled
    public String greenhouseProperty{get;set;}
    
    @AuraEnabled
    public String updateRules{get;set;}
    
    @AuraEnabled
    public String salesforceId{get;set;} 
    
    @AuraEnabled
    public String greenhouseObject{get;set;}  
    
    @AuraEnabled
    public Boolean synField{get;set;}  
    
    @AuraEnabled
    public String greenhouseParentObject{get;set;}  
    
    @AuraEnabled
    public Boolean required{get;set;}
    
    @AuraEnabled
    public String salesforceReferenceField{get;set;}
    
}